### ISSUE TITLE
Author field in datasets tab of excel reports not displaying correctly

### ISSUE THREAD

**Issue by eunices** [TexasDigitalLibrary/dataverse-reports#13]
Hello, the `author` field in `datasets` tab of the excel report does not seem to be displaying correctly when there are multiple authors. Dummy data from dataverse was used.

A fix is probably required in `reports/dataset.py` `get_value_recursive` method. 

Here's an illustration of the problem: 

- This is the display info of the authors
<img width="1276" alt="Screenshot 2021-10-15 at 4 59 59 PM" src="https://user-images.githubusercontent.com/4596893/137461672-d82af9f2-2407-4895-94fc-62e2ecf69cae.png">

- This is part of the JSON output from endpoint /api/datasets/:persistentId/?persistentId={doi}. Json is attached as zip. [json.zip](https://github.com/TexasDigitalLibrary/dataverse-reports/files/7352290/json.zip)
```json
                    {
                  
                        "typeName": "author",
                        "multiple": true,
                        "typeClass": "compound",
                        "value": [
                            {
                                "authorName": {
                                    "typeName": "authorName",
                                    "multiple": false,
                                    "typeClass": "primitive",
                                    "value": "Didegah"
                                },
                                "authorAffiliation": {
                                    "typeName": "authorAffiliation",
                                    "multiple": false,
                                    "typeClass": "primitive",
                                    "value": "University of British Columbia"
                                }
                            },
                            {
                                "authorName": {
                                    "typeName": "authorName",
                                    "multiple": false,
                                    "typeClass": "primitive",
                                    "value": "Ghaseminik, Zahra"
                                },
                                "authorAffiliation": {
                                    "typeName": "authorAffiliation",
                                    "multiple": false,
                                    "typeClass": "primitive",
                                    "value": "Scientometrics & Technological Investigation Research Group"
                                },
                                "authorIdentifierScheme": {
                                    "typeName": "authorIdentifierScheme",
                                    "multiple": false,
                                    "typeClass": "controlledVocabulary",
                                    "value": "ORCID"
                                }
                            },
                            {
                                "authorName": {
                                    "typeName": "authorName",
                                    "multiple": false,
                                    "typeClass": "primitive",
                                    "value": "Alperin, Juan Pablo"
                                },
                                "authorAffiliation": {
                                    "typeName": "authorAffiliation",
                                    "multiple": false,
                                    "typeClass": "primitive",
                                    "value": "Simon Fraser University"
                                },
                                "authorIdentifierScheme": {
                                    "typeName": "authorIdentifierScheme",
                                    "multiple": false,
                                    "typeClass": "controlledVocabulary",
                                    "value": "ORCID"
                                },
                                "authorIdentifier": {
                                    "typeName": "authorIdentifier",
                                    "multiple": false,
                                    "typeClass": "primitive",
                                    "value": "http://orcid.org/0000-0002-9344-7439"
                                }
                            }
                        ]
                    },
```

- The excel output looks like this, and is not displaying correctly. It increments and concatenates the list of authors, resulting in duplicated authors in datasets with multiple authors.

Didegah - University of British Columbia ; Didegah - University of British ColumbiaGhaseminik, Zahra - Scientometrics & Technological Investigation Research Group - ORCID ; Didegah - University of British ColumbiaGhaseminik, Zahra - Scientometrics & Technological Investigation Research Group - ORCIDAlperin, Juan Pablo - Simon Fraser University - ORCID - http://orcid.org/0000-0002-9344-7439

It should instead be:
Didegah - University of British Columbia; Ghaseminik, Zahra - Scientometrics & Technological Investigation Research Group - ORCID; Alperin, Juan Pablo - Simon Fraser University - ORCID - http://orcid.org/0000-0002-9344-7439

<img width="1317" alt="Screenshot 2021-10-15 at 5 08 24 PM" src="https://user-images.githubusercontent.com/4596893/137462914-b8f9858f-cb33-409d-8665-b5d4a45c828e.png">

**Comment by nwoodward** [comment]
Hi. Thanks for bringing this issue to my attention. I vaguely recall something about this from when they switched to multiple authors in the API response. I'll take a look at the code and get back to you.

**Comment by nwoodward** [comment]
Hi @eunices. I'm sorry for the long delay. I realized this didn't have to do with the API response but was an issue with how the code handles compound metadata fields. So it took me a while to find some time to come up with a solution. I've committed a possible fix for multiple authors in datasets to the develop branch that works for me, but it would be great if you could test it on your data before I create a new release.

**Comment by eunices** [comment]
Hi @nwoodward, changes look good. Thanks so much!

<img width="1156" alt="Screenshot 2021-12-06 at 2 03 05 PM" src="https://user-images.githubusercontent.com/4596893/144795666-a425ee44-1d8e-4dc9-9232-ae7ff5e91fe1.png">
