### ISSUE TITLE
git as a dependency for pipenv

### ISSUE THREAD

**Issue by eunices** [TexasDigitalLibrary/dataverse-reports#16]
Hi, could confirm if git is a dependency for pipenv? 

Appreciate the confirmation.

**Comment by nwoodward** [comment]
Hi Eunice,
If I'm understanding you correctly, git is not a dependency for pipenv by itself, but it in the case of this repository it **is** required in order to get the "dataverse" package from GitHub. Does that make sense?

Nick

**Comment by eunices** [comment]
Yes, got it! Thanks!
